version: "3"

services:
  ##################################
  # Setup client container
  # Runs nginx and serves react app
  ##################################
  client:
    build: ./client
    image: web3testing.azurecr.io/unitynftservice-client:latest
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    ports:
      - 80:80
    links:
      - server

  #########################
  # Setup node container
  #########################
  server:
    build: ./server
    image: web3testing.azurecr.io/unitynftservice-server:latest
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      MONGODB_CONNSTRING: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb
      ALCHEMY_API_KEY: ${ALCHEMY_API_KEY}
    command: ${NODE_COMMAND:-node} index.js
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    links:
      - mongodb

  ##########################
  # Setup database container
  ##########################
  mongodb:
    image: mongo:6.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}